apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-app-reader-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: policy-job-service-account  
    namespace: argocd
roleRef:
  kind: Role
  name: argo-app-reader
  apiGroup: rbac.authorization.k8s.io